import { contextBridge, ipcRenderer } from "electron";
import type { ConfigPatch, DiscoveryResult, EffectiveConfig, GatewayPool, GatewayUpstreamHealth, ManagedSurfaceEntry, ProfileRef, SessionListPage, SessionMessagePage, SessionRefreshStats, SessionSearchResult, Snapshot, SurfaceBundle, UpdateStatus } from "@omp-switch/core";

const api = {
  getInfo: () => ipcRenderer.invoke("app:info"),
  setTheme: (theme: "light" | "dark" | "system") => ipcRenderer.invoke("app:set-theme", theme),
  listProfiles: (): Promise<ProfileRef[]> => ipcRenderer.invoke("omp:list-profiles"),
  loadProfile: (profileId: string): Promise<EffectiveConfig> => ipcRenderer.invoke("omp:load-profile", profileId),
  save: (profileId: string, patch: ConfigPatch) => ipcRenderer.invoke("omp:save", profileId, patch),
  preview: (profileId: string, patch: ConfigPatch): Promise<{ preview: import("@omp-switch/core").PatchPreview; modelsText: string; settingsText: string }> => ipcRenderer.invoke("omp:preview", profileId, patch),
  listSnapshots: (profileId: string): Promise<Snapshot[]> => ipcRenderer.invoke("omp:list-snapshots", profileId),
  snapshot: (profileId: string): Promise<Snapshot> => ipcRenderer.invoke("omp:snapshot", profileId),
  restore: (profileId: string, snapshotId: string, options?: { force?: boolean }) => ipcRenderer.invoke("omp:restore", profileId, snapshotId, options),
  restoreLatest: (profileId: string) => ipcRenderer.invoke("omp:restore-latest", profileId),
  discover: (options: { baseUrl: string; apiKey?: string; headers?: Record<string, string>; timeoutMs?: number; type?: "ollama" | "llama.cpp" | "lm-studio" | "openai-models-list" | "proxy" | "litellm" }): Promise<DiscoveryResult> => ipcRenderer.invoke("omp:discover", options),
  listCatalog: (query?: string) => ipcRenderer.invoke("catalog:list", query),
  importCatalog: (bundle: unknown) => ipcRenderer.invoke("catalog:import", bundle),
  exportCatalog: () => ipcRenderer.invoke("catalog:export"),
  projectOverlay: (profileId = "default") => ipcRenderer.invoke("project:overlay", profileId),
  chooseProjectRoot: (profileId = "default", title?: string) => ipcRenderer.invoke("project:choose-root", profileId, title),

  listSurface: (profileId: string, kind: "prompt" | "skill"): Promise<ManagedSurfaceEntry[]> => ipcRenderer.invoke("surface:list", profileId, kind),
  readSurface: (profileId: string, kind: "prompt" | "skill", name: string): Promise<string> => ipcRenderer.invoke("surface:read", profileId, kind, name),
  writeSurface: (profileId: string, kind: "prompt" | "skill", name: string, content: string): Promise<ManagedSurfaceEntry> => ipcRenderer.invoke("surface:write", profileId, kind, name, content),
  deleteSurface: (profileId: string, kind: "prompt" | "skill", name: string): Promise<void> => ipcRenderer.invoke("surface:delete", profileId, kind, name),
  exportSurfaces: (profileId: string): Promise<SurfaceBundle> => ipcRenderer.invoke("surface:export", profileId),
  importSurfaces: (profileId: string, bundle: SurfaceBundle): Promise<ManagedSurfaceEntry[]> => ipcRenderer.invoke("surface:import", profileId, bundle),
  refreshSessions: (profileId: string, options: { rebuild?: boolean } = {}): Promise<SessionRefreshStats> => ipcRenderer.invoke("session:refresh", profileId, options),
  listSessions: (profileId: string, options: { limit?: number; cursor?: string } = {}): Promise<SessionListPage> => ipcRenderer.invoke("session:list", profileId, options),
  searchSessionFts: (profileId: string, query: string, limit?: number): Promise<SessionSearchResult[]> => ipcRenderer.invoke("session:search-fts", profileId, query, limit),
  readSessionMessages: (profileId: string, id: string, options: { cursor?: string } = {}): Promise<SessionMessagePage> => ipcRenderer.invoke("session:messages", profileId, id, options),
  usageSummary: (profileId = "default", options: { from?: string; to?: string; reindex?: boolean } = {}) => ipcRenderer.invoke("usage:summary", profileId, options),
  setUsagePrice: (key: string, price: { input?: number; output?: number; cacheRead?: number; cacheWrite?: number } | null) => ipcRenderer.invoke("usage:set-price", key, price),
  listGatewayPools: (profileId?: string): Promise<GatewayPool[]> => ipcRenderer.invoke("gateway:list", profileId),
  saveGatewayPool: (pool: GatewayPool): Promise<GatewayPool> => ipcRenderer.invoke("gateway:save", pool),
  gatewayStatus: () => ipcRenderer.invoke("gateway:status"),
  gatewayHealth: (poolId?: string): Promise<Record<string, GatewayUpstreamHealth>> => ipcRenderer.invoke("gateway:health", poolId),
  probeGatewayUpstream: (arg1: string, arg2: string, arg3?: string | number, arg4?: number) => ipcRenderer.invoke("gateway:probe", arg1, arg2, arg3, arg4),
  startGateway: (profileId: string) => ipcRenderer.invoke("gateway:start", profileId),
  stopGateway: () => ipcRenderer.invoke("gateway:stop"),
  updateOmp: (profileId = "default") => ipcRenderer.invoke("omp:update", profileId),
  secretPut: (input: { id?: string; label: string; value: string }): Promise<{ id: string; command: string }> => ipcRenderer.invoke("secret:put", input),
  secretStatus: (id: string) => ipcRenderer.invoke("secret:status", id),
  secretDelete: (id: string, force?: boolean) => ipcRenderer.invoke("secret:delete", id, force),
  secretOrphans: (profileId = "default") => ipcRenderer.invoke("secret:orphans", profileId),

  authStatus: (provider: string): Promise<{ ok: boolean; output: string; code?: string; error?: string }> => ipcRenderer.invoke("omp:auth-status", provider),
  authLogin: (provider: string): Promise<{ ok: boolean; output: string; code?: string; error?: string }> => ipcRenderer.invoke("omp:auth-login", provider),

  checkForUpdates: (force?: boolean): Promise<UpdateStatus | null> => ipcRenderer.invoke("update:check", force),
  updateStatus: (): Promise<{ enabled: boolean; lastCheckAt: string | null; lastResult: UpdateStatus | null }> => ipcRenderer.invoke("update:status"),
  setUpdateCheckEnabled: (enabled: boolean): Promise<void> => ipcRenderer.invoke("update:set-enabled", enabled),
  openExternal: (url: string): Promise<void> => ipcRenderer.invoke("app:open-external", url),
};

contextBridge.exposeInMainWorld("ompSwitch", api);
